# Generated by Django 4.0.5 on 2022-06-08 15:24

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transcriptions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transcription',
            name='chart',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='Sheet Music'),
        ),
    ]
