# Generated by Django 4.0.5 on 2022-06-23 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_remove_review_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-created_on']},
        ),
        migrations.AddField(
            model_name='review',
            name='reviewed',
            field=models.BooleanField(default=True),
        ),
    ]
