# Generated by Django 4.0.5 on 2022-06-23 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_alter_review_options_review_reviewed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='reviewed',
        ),
    ]
