# Generated by Django 4.0.5 on 2022-06-15 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faqs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='body',
            field=models.TextField(max_length=1000),
        ),
    ]
