# Generated by Django 4.0.5 on 2022-06-15 13:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('faqs', '0002_alter_faq_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
