# Generated by Django 4.0.5 on 2022-06-15 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faqs', '0003_faq_created_on'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Faq',
            new_name='Question',
        ),
    ]
