# Generated by Django 4.0.5 on 2022-06-09 15:29

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('video', cloudinary.models.CloudinaryField(max_length=255, verbose_name='Video Lesson')),
                ('body', models.TextField(max_length=500)),
                ('type', models.CharField(choices=[('txt', 'Text'), ('vid', 'Video')], max_length=3)),
                ('status', models.IntegerField(choices=[('Draft', 0), ('published', 1)], default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='drum_lesson', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
