# Generated by Django 4.0.5 on 2022-06-09 15:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_lesson_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['title']},
        ),
        migrations.RenameField(
            model_name='lesson',
            old_name='type',
            new_name='format',
        ),
        migrations.AddField(
            model_name='lesson',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
