# Generated by Django 4.0.5 on 2022-06-09 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0003_alter_lesson_options_rename_type_lesson_format_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='status',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'published')], default=0),
        ),
    ]
